menu_page = "title";
test_title_frames = 0;
menu_selection = 0;
menu_buttons = bb_menu_layout(menu_page);
menu_mouse_x = device_mouse_x_to_gui(0);
menu_mouse_y = device_mouse_y_to_gui(0);
audio_stop_all();
audio_play_sound(snd_mus_intro, 1, false);
audio_play_sound(snd_bal_menu, 2, false);
window_set_cursor(cr_default);
window_mouse_set_locked(false);
